### ISSUE TITLE
[BUG]: 启动报错TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Z735803792** [A-kirami/nonebot-plugin-chatgpt#1]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.1.0

### 问题描述

启动报错，无法运行插件

### 复现步骤

1、ubuntu20.04,python3.9.15,nonebot2==2.0.0b5
2、在src.plugins.下git clone
3、根据readme填写TOKEN
4、启动nb端

### 预期行为

正常启动

### 实际行为

报错，无法正常启动

### 日志信息

![image](https://user-images.githubusercontent.com/70925546/205644897-92160da3-5f40-49de-8e24-dbecff0935b0.png)

**Comment by MiZhouWellsleep** [comment]
今天装了下也还是碰到这个问题了，将"nonebot_plugin_chatgpt"文件夹放src.plugins里，TOKEN也按要求填写了，还是碰到了"unsupported operand type(s) for |: 'type' and 'NoneType'"的报错

**Comment by A-kirami** [comment]
> 

你是直接git的？

**Comment by MiZhouWellsleep** [comment]
> > 我今天装这个插件也碰到这个问题了，操作流程也是这样，也还是碰到了unsupported operand type(s) for |: 'type' and 'NoneType'的报错
> 
> 你是直接git的？

啊抱歉已经解决了，应该是我之前装的时候出问题了，现在一切正常
