### ISSUE TITLE
[Feature]: command和tome同时设置不生效？

### ISSUE THREAD

**Issue by QNLanYang** [A-kirami/nonebot-plugin-chatgpt#127]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

chatgpt_command和chatgpt_to_me同时设置时无法响应消息
例如我的command设置为"."，to_me为true
这样设置时无论私聊或在群聊中，无论先.后@还是先@后.都不会触发matcher
包括nonebot的command无论有没有“.”都是不响应
因为我加载了其他的两个on_message触发的插件所以希望同时开启tome和command

### 您想要的解决方案

只要解答一下这两个参数的具体设置以及用例就好了

**Comment by QNLanYang** [comment]
找到原因了。
代码里面在构建matcher时，没有设置gpt_cmd的响应类型是on_msg
当设置gpt_cmd时响应类型是on_cmd。
也就是说当你两个命令前缀都不为空的时候你需要用下面格式：
[bot命令前缀]+[插件命令前缀]+【内容】
才可以触发插件的响应。。。

**Comment by A-kirami** [comment]
设计如此，如果你不需要bot自带的命令前缀，可以考虑在env中的bot的命令前缀里添加一个空前缀
