### ISSUE TITLE
[BUG]: 私聊或at没反应

### ISSUE THREAD

**Issue by Sincejunly** [A-kirami/nonebot-plugin-chatgpt#13]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

目前最新的版本

### 问题描述

机器人无响应

### 复现步骤

我已在https://chat.openai.com/chat 登录了账号并设置
token=xxxx
之前尝试token=“xxxx”
添加了CHATGPT_COMMAND=""
但是私聊机器人它没反应 我有全局代理

### 预期行为

回复消息

### 实际行为

无响应，但是我自己写的插件可以正常响应

### 日志信息

我不知道日志在哪里，但是主窗口没有错误内容

**Comment by hv0905** [comment]
解决了，机器人似乎只支持Onebot V11
