### ISSUE TITLE
[Feature]: 是否有计划增加简单的指令使得bot可以转换为txt文件并发送，以及对图片的识别？

### ISSUE THREAD

**Issue by Sincejunly** [A-kirami/nonebot-plugin-chatgpt#14]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

增加简单的指令使得bot可以转换为txt文件并发送
对图片的识别

### 您想要的解决方案

通过对话可以添加单次指令 使得bot可以转换为txt文件并发送，并可以在设置中设置bot默认使用txt文件回复或者其它形式回复
对图片的识别

**Comment by A-kirami** [comment]
我没有理解是在什么场景下，才会需要这种功能，请详细描述一下使用场景

**Comment by Jerry-FaGe** [comment]
> 我没有理解是在什么场景下，才会需要这种功能，请详细描述一下使用场景

可能是想抄代码但配置文件已经设置成只发图片了，命令中加个可选参数使这次请求无视配置文件只发文本应该就可以解决

**Comment by Sincejunly** [comment]
> 我没有理解是在什么场景下，才会需要这种功能，请详细描述一下使用场景

文本太多了，有的时候不想这样

**Comment by Sincejunly** [comment]
> > 我没有理解是在什么场景下，才会需要这种功能，请详细描述一下使用场景
> 
> 可能是想抄代码但配置文件已经设置成只发图片了，命令中加个可选参数使这次请求无视配置文件只发文本应该就可以解决

对，我也这样想，实在不行的话 我自己改一改也是可以的

**Comment by A-kirami** [comment]
从上面的描述来看，这可能不是一个具有普适性的需求，因此此需求暂时不会添加到计划中。

如果你有这方面的需要，可以 fork 仓库自行修改使用。
