### ISSUE TITLE
[BUG]: 使用账密登录会报Exception: State not found

### ISSUE THREAD

**Issue by forchannot** [A-kirami/nonebot-plugin-chatgpt#18]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.4.0

### 问题描述

通过账密登录会报Exception: State not found错，账密确认没错，代理没问题，通过ssion访问是没问题的

### 复现步骤

账密登录

**Comment by A-kirami** [comment]
acheong08/ChatGPT 的 issue 评论中认为这是代理的问题，代理 IP 被列入了黑名单，可以更换代理或者使用 session token 登陆。
https://github.com/acheong08/ChatGPT/issues/134
![image](https://user-images.githubusercontent.com/66513481/206709791-eff53f40-a1db-4415-8d32-5cd799f97e75.png)
