### ISSUE TITLE
[BUG]: 无法找到__Secure-next-auth.session-token

### ISSUE THREAD

**Issue by Goodzzzz** [A-kirami/nonebot-plugin-chatgpt#19]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

v0.4.0

### 问题描述

根据教程，在 https://chat.openai.com/chat网址按下F12，切换到 Application/应用 选项卡，找到 Cookies，但是无法找到__Secure-next-auth.session-token。

### 复现步骤

1.按 F12 打开控制台
切换到 Application/应用 选项卡，找到 Cookies
2.然后并没有找到__Secure-next-auth.session-token这个Name

**Comment by CG-15** [comment]
登陆之后试试

**Comment by A-kirami** [comment]
无法确认具体问题，这边依然能够看到 `__Secure-next-auth.session-token`

![image](https://user-images.githubusercontent.com/66513481/206212212-5d3fb827-5763-40b6-8c57-2cfc023a8251.png)

**Comment by Goodzzzz** [comment]
chatgpt官网问题，第二天再看就有了
