### ISSUE TITLE
[Question]: 我调高了优先级，但是不能向下阻断

### ISSUE THREAD

**Issue by zhulinyv** [A-kirami/nonebot-plugin-chatgpt#20]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

我将 `params: Dict[str, Any] = {"priority": 999}` 改为了 50 ，可是这样不能向下阻断，
我尝试加入 `block = True` ，可是我不知道加在哪里TAT。

### 您想要的解决方案

增加一个阻断。

**Comment by A-kirami** [comment]
已允许自定义此配置
