### ISSUE TITLE
[BUG]: 图片不全

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [A-kirami/nonebot-plugin-chatgpt#21]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.4.0

### 问题描述

以图片形式输出，当其中出现代码的时候，就会超出图片大小，从而无法显示

### 复现步骤

向bot提出一个问题，使其回复中包含代码

### 预期行为

完整的输出

### 实际行为

![image](https://user-images.githubusercontent.com/70925546/206388825-c542ccc4-1f90-4733-8e5b-3ac21c3b1b32.png)

**Comment by A-kirami** [comment]
这是一个上游问题，它来自[nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)，我无法处理它，只能添加一个自定义配置来设置图像的宽度。
