### ISSUE TITLE
[Feature]: 大佬能不能改一下命令方式，改成"提问"或"对话"啥可修改的

### ISSUE THREAD

**Issue by MoKeNeng** [A-kirami/nonebot-plugin-chatgpt#23]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

我的nonebot在调用chatgpt的时候会和另一个聊天ai插件冲突，所以我不得不只选择其中一个进行启动，但我想要两个同时启动，以另一个ai为主，chatgpt为辅。

### 您想要的解决方案

修改命令方式，不是@机器人启动，而是通过"对话"，“提问”等字符串启动，这样就可以两个一起用啦。希望大佬能康康我的问题。

**Comment by zhulinyv** [comment]
> 

```
CHATGPT_TO_ME = False
CHATGPT_COMMAND = ["对话", "提问"]
```

**Comment by MoKeNeng** [comment]
好的，我康康，谢谢
