### ISSUE TITLE
[Feature]: 增加 CDtime 来防止请求过频繁造成的 ReadTimeout: 

### ISSUE THREAD

**Issue by zhulinyv** [A-kirami/nonebot-plugin-chatgpt#24]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

ReadTimeout 退退退！！

### 您想要的解决方案

增加 CDtime

**Comment by A-kirami** [comment]
实现时最好能够告知用户剩余cd时间
