### ISSUE TITLE
[Feature]: 对于群聊对话context的建议

### ISSUE THREAD

**Issue by zhenyuefu** [A-kirami/nonebot-plugin-chatgpt#28]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

目前在群聊中每一个用户拥有独立的对话，但在群聊中本就是所以用户都能看见的对话，所以希望能够在群聊中以群为范围保存对话context。

### 您想要的解决方案

每一个群中的对话都是连续的，同一个群的不同用户在群聊中默认加入同一个conversation

**Comment by A-kirami** [comment]
我不确定这是否是一个所有人都能接受的改动，如果有人支持或反对，可以在此 issue 评论。

**Comment by sena-nana** [comment]
我认为或许可以在设置中加入global选项？或者由群主或管理员使用指令将某一个id作为该群的全局会话。
每个人都可以和同一个性格的AI对话我认为是有必要的功能。但是保持风格独立也有其使用场景。
我认为应该把选择权交给用户

**Comment by MoKeNeng** [comment]
请问您是已经解决了这个问题吗。我应该如何修改使用他，能不能教一教0.0

**Comment by A-kirami** [comment]
> 请问您是已经解决了这个问题吗。我应该如何修改使用他，能不能教一教0.0

更新最新版本，参考readme配置
