### ISSUE TITLE
[BUG]: 无法在Arm设备上运行本插件

### ISSUE THREAD

**Issue by uiharuayako** [A-kirami/nonebot-plugin-chatgpt#29]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [x] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.5.1

### 问题描述

我一般用树莓派设备来挂nonebot，树莓派是arm64架构的，今天运行这个插件的时候报错了，看了一下log，发现本插件调用了OpenAIAuth包来实现使用openai的账号密码获取token，而这个包调用了tls_client包，tls_client试图调用一个dll的时候，我的设备上就报错了。

看了一下https://github.com/acheong08/ChatGPT的readme，里面写的“
No ARM support for email/password. Use session token authentication if on Raspberry Pi”。发现不需要OpenAIAuth只用token应该也能登录，就把插件里涉及OpenAIAuth的几行代码删了，发现能正常运行

### 复现步骤

1. 安装插件，并未报错
2. 运行nonebot服务，chatgpt插件报错，其他功能正常
3. 卸载并重新安装插件，错误依然存在，卸载并重新安装tls_client包，换用不同版本的OpenAIAuth包，重复步骤1 2，错误依然存在

**Comment by A-kirami** [comment]
在不修改代码的情况下，只使用 token 是否可以正常登录

**Comment by uiharuayako** [comment]
不修改代码的情况下，在arm设备应该是无法正常登录的

**Comment by A-kirami** [comment]
> 不修改代码的情况下，在arm设备应该是无法正常登录的

在token模式下，只是在头部导入，但没有使用登录功能，应该不会引起问题。但是我不能确定，能否麻烦测试一下呢。

**Comment by uiharuayako** [comment]
> > 不修改代码的情况下，在arm设备应该是无法正常登录的
> 
> 在token模式下，只是在头部导入，但没有使用登录功能，应该不会引起问题。但是我不能确定，能否麻烦测试一下呢。

重现了一下，插件加载失败了，报错如下，之后尝试@bot来发送消息也没有反应
![安装截图](https://user-images.githubusercontent.com/52899485/206852938-720a93a8-fc74-4e87-8d7d-6190b960c37e.png)
![运行截图](https://user-images.githubusercontent.com/52899485/206852939-eae2b217-2eb7-4e40-ae27-c00ec523393c.png)
![尝试发送消息](https://user-images.githubusercontent.com/52899485/206853069-03a00bd5-e9eb-41bf-ad1a-38d0a6bce4d1.png)

**Comment by hecheng337** [comment]
> 在不修改代码的情况下，只使用 token 是否可以正常登录
我这边测试是没问题的。
