### ISSUE TITLE
[BUG]:  HTTP401

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [A-kirami/nonebot-plugin-chatgpt#35]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.5.2

### 问题描述

TOKEN已经配置，账号密码也配置了，也挂代理了，但是总是出401

### 复现步骤

chat 测试

### 预期行为

正常回复

### 实际行为

返回图片![image](https://user-images.githubusercontent.com/70925546/206866453-614e6161-c29d-46dd-8927-d6cb17d657d6.png)

### 日志信息

12-11 00:55:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_chatgpt)
12-11 00:55:51 [ERROR] nonebot_plugin_chatgpt | 非预期的响应内容: HTTP401 {"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}}

### 额外补充

python3.9.15,ubuntu20.04

**Comment by A-kirami** [comment]
token 过期，更换 token

**Comment by Umamusume-Agnes-Digital** [comment]
替换了好几次了，web端都是正常使用，但bot这里就401了

**Comment by Umamusume-Agnes-Digital** [comment]
换谷歌浏览器登录，获取token可以了。。。。
