### ISSUE TITLE
[Feature]: 加入储存数据并在重启后自动读取的功能

### ISSUE THREAD

**Issue by sena-nana** [A-kirami/nonebot-plugin-chatgpt#38]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

目前，每次机器人重启后，之前保存的会话数据，cookie数据都会丢失，而此时config文档中的cookie也已经过期了，这就需要再重新获取cookie很麻烦

### 您想要的解决方案

每次刷新会话时，将当前的cookie保存至json文件，在下一次启动时，读取json文件的cookie，优先用已保存的cookie，无效再取设置，再无效就抛出错误。

需要在刷新会话的部分加入保存数据的逻辑，并在初始化config的部分加入读取数据的逻辑

**Comment by A-kirami** [comment]
目前已经有保存会话与切换会话功能，感觉自动保存的必要性不是很大。

**Comment by sena-nana** [comment]
其实主要是想保存token（

**Comment by A-kirami** [comment]
你将如何检查 config 中的 token 是否更新？

**Comment by sena-nana** [comment]
最朴素的方法，json中存储上一次config的token值，只要一比对就好了

**Comment by A-kirami** [comment]
> 最朴素的方法，json中存储上一次config的token值，只要一比对就好了

……果然，但是感觉多了冗余数据

**Comment by sena-nana** [comment]
如果要实现这个，肯定要存点什么的……
不过从功能实现上，甚至不需要比对，因为json里的是已经确定可用的，可以直接拿来初始化，如果json里的不可用，再去config里去取，这样就不需要存储了

**Comment by A-kirami** [comment]
那就按你说的，优先用已保存的吧，无效再取设置，再无效就抛出错误。
如果你不打算自动保存会话的话，可以把issue修改一下。

**Comment by sena-nana** [comment]
那我先修改一下吧，自动保存会话的功能可以先看看其他人有没有类似的需求再说。毕竟有保存会话功能在

**Comment by sena-nana** [comment]
我看了下代码，目前的保存会话好像并不能够保证重启后依旧可用？
