### ISSUE TITLE
[BUG]: 请问是不是只支持onebot v11传来的消息？其他适配器传来消息会被skipped？

### ISSUE THREAD

**Issue by junnanjiang** [A-kirami/nonebot-plugin-chatgpt#39]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.6.0

### 问题描述

使用[adapter-ntchat](https://github.com/JustUndertaker/adapter-ntchat)+[ntchat-client](https://github.com/JustUndertaker/ntchat-client)可以收到消息，而且会被handler处理，但是会skipped。。
log如下：

> 12-11 18:18:47 [SUCCESS] nonebot | ntchat wxid_7e62t4v31ne322 | [MT_RECV_TEXT_MSG]: Message 9024582476765405967 from Run: //0728hello
> 12-11 18:18:47 [DEBUG] nonebot | Checking for matchers in priority 1...
> 12-11 18:18:47 [DEBUG] nonebot | Checking for matchers in priority 10...
> 12-11 18:18:47 [DEBUG] nonebot | Checking for matchers in priority 999...
> 12-11 18:18:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
> 12-11 18:18:47 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
> 12-11 18:18:47 [DEBUG] nonebot | Running handler Dependent(call=ai_chat, parameterless=(Depends(Dependent(call=check_cooldown)),))
> 12-11 18:18:47 [DEBUG] nonebot | Handler Dependent(call=ai_chat, parameterless=(Depends(Dependent(call=check_cooldown)),)) skipped
> 12-11 18:18:47 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_chatgpt.utils) running complete
> 12-11 18:18:47 [DEBUG] nonebot | Stop event propagation

### 复现步骤

1.NB2里安装了ntchat适配器`nb adapter install nonebot-adapter-ntchat`
2.下载了[ntchat-client](https://github.com/JustUndertaker/ntchat-client)并启动，可以在NB2里收到消息
3.收到消息且触发了handler，但会被skipped

（使用onebot v11收到的消息可以正常处理，不会被skipped）

### 日志信息

> 12-11 18:18:47 [SUCCESS] nonebot | ntchat wxid_7e62t4v31ne322 | [MT_RECV_TEXT_MSG]: Message 9024582476765405967 from Run: //0728hello
> 12-11 18:18:47 [DEBUG] nonebot | Checking for matchers in priority 1...
> 12-11 18:18:47 [DEBUG] nonebot | Checking for matchers in priority 10...
> 12-11 18:18:47 [DEBUG] nonebot | Checking for matchers in priority 999...
> 12-11 18:18:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
> 12-11 18:18:47 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
> 12-11 18:18:47 [DEBUG] nonebot | Running handler Dependent(call=ai_chat, parameterless=(Depends(Dependent(call=check_cooldown)),))
> 12-11 18:18:47 [DEBUG] nonebot | Handler Dependent(call=ai_chat, parameterless=(Depends(Dependent(call=check_cooldown)),)) **skipped**
> 12-11 18:18:47 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_chatgpt.utils) running complete
> 12-11 18:18:47 [DEBUG] nonebot | Stop event propagation

**Comment by A-kirami** [comment]
本插件基于 onebot v11 适配器编写，如果需要支持其他适配器，请 fork 后自行修改适配。
