### ISSUE TITLE
[Feature]: 回答不满意，重新回答。

### ISSUE THREAD

**Issue by MoKeNeng** [A-kirami/nonebot-plugin-chatgpt#43]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

有时候，QQchatgpt的回答并不让我满意，我想让他重新回答。

### 您想要的解决方案

我发现chatgpt网站上有个刷新按钮，一按就可以让他重新回答，不知道大佬能不能把这个按钮变成“重新回答”这样的指令。

**Comment by ddlixin** [comment]
不能用了？
An error occurred. If this issue persists please contact us through our help center at help.openai.com.

**Comment by MoKeNeng** [comment]
这个插件是可以用的啊。我的意思是能不能加一个功能实现我上面写的问题。

**Comment by MoKeNeng** [comment]
readme没更新，我该用啥指令来回滚会话？

**Comment by A-kirami** [comment]
> readme没更新，我该用啥指令来回滚会话？

已更新 README
