### ISSUE TITLE
[QUESTION]: Tag "<head>" does not correspond to any known ansi directive,

### ISSUE THREAD

**Issue by Dragon-ts** [A-kirami/nonebot-plugin-chatgpt#44]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

Latest

### 问题描述

无法使用nonebot-plugin-chatgpt插件进行QQ机器人对话
我尝试了重新安装该插件，但是没有解决此问题

### 复现步骤

1.`pip install nonebot-plugin-chatgpt -i https://pypi.tuna.tsinghua.edu.cn/simple`
2.在.env中添加了`CHATGPT_SESSION_TOKEN`
3.在qq中@机器人发送任意消息，回复了以下信息
_请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: ValueError: Tag "<head>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)_

### 预期行为

如OpenAI的ChatGPT那样回复

### 实际行为

报出错误:
QQ:_请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: ValueError: Tag "<head>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)_

后台:
```
nonebot_plugin_chatgpt | ChatGPT request failed: ValueError: Tag "<head>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
Traceback (most recent call last):
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
ValueError: Tag "<head>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
```

### 日志信息

`[ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: ValueError: Tag "<head>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 128, in refresh_session
    self.authorization = response.json()['accessToken']
  File "C:\Program Files\Python310\lib\site-packages\httpx\_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EnderDragon\EnderDragon3rd\bot.py", line 13, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Program Files\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Program Files\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Program Files\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Program Files\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Program Files\Python310\lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 59, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "C:\Program Files\Python310\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 86, in get_chat_response
    await self.refresh_session()
  File "C:\Program Files\Python310\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 130, in refresh_session
    logger.opt(colors=True, exception=e).error(
  File "C:\Program Files\Python310\lib\site-packages\loguru\_colorizer.py", line 369, in prepare_simple_message
    parser.feed(string)
  File "C:\Program Files\Python310\lib\site-packages\loguru\_colorizer.py", line 253, in feed
    raise ValueError(
ValueError: Tag "<head>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)`

**Comment by Dragon-ts** [comment]
![image](https://user-images.githubusercontent.com/106637358/206939870-f4ff37a8-7c32-4fb6-a42b-7d014c7be67b.png)

**Comment by JoeMax01** [comment]
我的机器人也嗝屁了，是官网那边的问题，好像是多加了层验证，反正API机器人不能用了

**Comment by Dragon-ts** [comment]
> 我的机器人也嗝屁了，是官网那边的问题，好像是多加了层验证，反正API机器人不能用了

openo官方的那个api是不是能用啊，我看pypi上的openai[https://pypi.org/project/openai](url)啥描述都没有

**Comment by Reversedeer** [comment]
我也是，昨晚凌晨就报错了，没来得及提Issues.....

**Comment by MingxuanGame** [comment]
加 cloudflare 了
 https://github.com/acheong08/ChatGPT/issues/261

**Comment by Harry-Jing** [comment]
https://github.com/acheong08/ChatGPT/issues/261
https://github.com/rawandahmad698/PyChatGPT/issues/71
https://github.com/transitive-bullshit/chatgpt-api/issues/96

**Comment by Reversedeer** [comment]
Well, it tells me if I bypass cloudflare。You have to translate him into Chinese to read
![image](https://user-images.githubusercontent.com/87823528/206945143-e44e235b-c0e2-490d-8e68-6e8155b3f51e.png)

**Comment by Dragon-ts** [comment]
so now what can we do to fix it
现在我们怎么修改才能使插件再次恢复到可用状态

**Comment by hv0905** [comment]
不知道直接用Playwright模拟浏览器可不可行

**Comment by SmallKi-d** [comment]
> 这个也许会有用https://github.com/VeNoMouS/cloudscraper

我尝试了一下，该插件的开源版本只能支持cloudflare v1，而chatGPT使用的是v2（作者还特意标注了free version，看来是有付费版）

**Comment by sena-nana** [comment]
由于当前版本的插件已经依赖了playwright，不会引入新的依赖，或许用playwright是个可行的方案

**Comment by SmallKi-d** [comment]
chatGPT 更新了，我看了一下，需要用到cf_clearance和user-agent,而且邮箱密码的验证方式无效了

**Comment by hv0905** [comment]
这个使用chromedriver绕过cf，但是chromedriver要有Chrome依赖，在无GUI linux上部署可能比较困难https://github.com/terry3041/pyChatGPT

**Comment by SmallKi-d** [comment]
> chatGPT 更新了，我看了一下，需要用到cf_clearance和user-agent,而且邮箱密码的验证方式无效了

我刚说完，作者就rollback了，草

**Comment by sena-nana** [comment]
> chatGPT 更新了，我看了一下，需要用到cf_clearance和user-agent,而且邮箱密码的验证方式无效了

我现在也定位到cf_clearance上了，但是直接让bot带有这个值并没有效果

**Comment by hv0905** [comment]
`cf_clearance` 要求登录机和服务器同ip并且大概1h就要手动更新一次（目前似乎没有简单的自动更新方案

**Comment by iHTCboy** [comment]
cf_clearance 与验证的设备的 IP 地址和用户代理的组合绑定，当前有效期为 2 小时。所以有没有人知道如何绕过 cloudflare ？

**Comment by chrisyy2003** [comment]
cloudflare 不是很好绕过，工程量比较大

**Comment by sena-nana** [comment]
抓了两个小时cloudflare的包我决定放弃，不是一般的麻烦（
不过或许可以通过接入官方的api来运行，虽然表现可能会和网页版不太一样

**Comment by HBLADEH** [comment]
😭😭😭

**Comment by chrisyy2003** [comment]
> 抓了两个小时cloudflare的包我决定放弃，不是一般的麻烦（ 不过或许可以通过接入官方的api来运行，虽然表现可能会和网页版不太一样

api如果便宜还好说

**Comment by Misaga10032** [comment]
所以这个插件是暂时寄了？如果我们找不到好的绕过cf的方法

**Comment by zhulinyv** [comment]
> > 抓了两个小时cloudflare的包我决定放弃，不是一般的麻烦（ 不过或许可以通过接入官方的api来运行，虽然表现可能会和网页版不太一样
> 
> api如果便宜还好说

每个账号好像有 15刀 的免费额度（

**Comment by Harry-Jing** [comment]
这个就是两格不同的模型了

**Comment by chrisyy2003** [comment]
> > > 抓了两个小时cloudflare的包我决定放弃，不是一般的麻烦（ 不过或许可以通过接入官方的api来运行，虽然表现可能会和网页版不太一样
> > 
> > 
> > api如果便宜还好说
> 
> 每个账号好像有 15刀 的免费额度（

18$大概能请求多少次

**Comment by chrisyy2003** [comment]
如果能够获取cf字段，我这个插件还是可以用的https://github.com/chrisyy2003/lingyin-bot，但是cf2小时过期
具体配置可以看这个文章：https://blog.chrisyy.top/qq-chatGPT.html#openai%E4%B8%8A%E4%BA%86Cloudflare%E4%B8%B4%E6%97%B6%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by Harry-Jing** [comment]
chathttps://github.com/acheong08/ChatGPT 的作者正在准备今天的一场考试，他说他会在今天放学后尝试解决

**Comment by Harry-Jing** [comment]
> 18$大概能请求多少次

1k的token 0.02美元

**Comment by Harry-Jing** [comment]
你们可以在这个群组中了解到开发进度 https://discord.gg/RvBkdcYUrH

**Comment by chrisyy2003** [comment]
> 你们可以在这个群组中了解到开发进度 https://discord.gg/RvBkdcYUrH

great

**Comment by zhulinyv** [comment]
> > > > 抓了两个小时cloudflare的包我决定放弃，不是一般的麻烦（ 不过或许可以通过接入官方的api来运行，虽然表现可能会和网页版不太一样
> > > 
> > > 
> > > api如果便宜还好说
> > 
> > 
> > 每个账号好像有 15刀 的免费额度（
> 
> 18$大概能请求多少次

[https://github.com/Special-Week/nonebot_plugin_smart_reply#%E5%85%B3%E4%BA%8Eopenai](https://github.com/Special-Week/nonebot_plugin_smart_reply#%E5%85%B3%E4%BA%8Eopenai)
18＄ 似乎并不能请求太多次（

**Comment by Prometheus-first** [comment]
现在应该怎么用呢，pip install 最新的版本之后还是报这个错

**Comment by Misaga10032** [comment]
我看内核代码那边的作者好像已经解决了，但是转移到nonebot上还是存在问题？

**Comment by Prometheus-first** [comment]
可能是我操作有误吧，我先是用pip uninstall nonebot-plugin-chatgpt把旧版本卸载了，然后pip install nonebot-plugin-chatgpt安装新版本，然后登陆chatgpt的官网去获取cookie，把.env里的cookie换成新的，但是启动之后还是报这个错

**Comment by sena-nana** [comment]
> 可能是我操作有误吧，我先是用pip uninstall nonebot-plugin-chatgpt把旧版本卸载了，然后pip install nonebot-plugin-chatgpt安装新版本，然后登陆chatgpt的官网去获取cookie，把.env里的cookie换成新的，但是启动之后还是报这个错

因为这边还没修……
我去看了上游库的更新，打算试一下看看能不能改一改运行起来

**Comment by Prometheus-first** [comment]
蹲一下，有可以运行的滴滴我，我想改，但是实力不够

**Comment by MingxuanGame** [comment]
我写了个 Playwright 的 demo

```py
import asyncio
import traceback

from playwright.async_api import async_playwright

js = "Object.defineProperties(navigator, {webdriver:{get:()=>undefined}});"


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            args=[
                "--disable-extensions",
                "--disable-application-cache",
                "--disable-gpu",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--incognito",
            ],
            proxy={"server": "http://192.168.31.3:9604"},   # your proxy
        )
        ua = f"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/{browser.version} Safari/537.36"
        content = await browser.new_context(user_agent=ua)
        page = await content.new_page()
        await page.add_init_script(js)
        try:
            await page.goto("https://chat.openai.com/chat")
            print("Sleep 10s")
            print(await page.content())
            await asyncio.sleep(10)
            print(await page.content())
            cookies = await content.cookies()
            cf = next(filter(lambda x: x["name"] == "cf_clearance", cookies))
            print(f"cf_clearance: {cf['value']}")
            print(f"user-agent: {ua}")
        except Exception:
            traceback.print_exc()
            # print(f"Raised an unexpected exception: {e}")
        finally:
            await page.close()
            await content.close()
            await browser.close()


asyncio.run(main())
```

（用了 `headless` 会弹验证码，所以设置为 `False`）

**Comment by chrisyy2003** [comment]
> 我写了个 Playwright 的 demo
> 
> ```python
> import asyncio
> import traceback
> 
> from playwright.async_api import async_playwright
> 
> js = "Object.defineProperties(navigator, {webdriver:{get:()=>undefined}});"
> 
> 
> async def main():
>     async with async_playwright() as p:
>         browser = await p.chromium.launch(
>             headless=False,
>             args=[
>                 "--disable-extensions",
>                 "--disable-application-cache",
>                 "--disable-gpu",
>                 "--disable-setuid-sandbox",
>                 "--disable-dev-shm-usage",
>                 "--incognito",
>             ],
>             proxy={"server": "http://192.168.31.3:9604"},   # your proxy
>         )
>         ua = f"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/{browser.version} Safari/537.36"
>         content = await browser.new_context(user_agent=ua)
>         page = await content.new_page()
>         await page.add_init_script(js)
>         try:
>             await page.goto("https://chat.openai.com/chat")
>             print("Sleep 10s")
>             print(await page.content())
>             await asyncio.sleep(10)
>             print(await page.content())
>             cookies = await content.cookies()
>             cf = next(filter(lambda x: x["name"] == "cf_clearance", cookies))
>             print(f"cf_clearance: {cf['value']}")
>             print(f"user-agent: {ua}")
>         except Exception:
>             traceback.print_exc()
>             # print(f"Raised an unexpected exception: {e}")
>         finally:
>             await page.close()
>             await content.close()
>             await browser.close()
> 
> 
> asyncio.run(main())
> ```
> 
> （用了 `headless` 会弹验证码，所以设置为 `False`）

无gui的linux服务器可以跑吗

**Comment by sena-nana** [comment]
> 牛哇牛哇，楼上的那位很赞，真绕过了，现在就差作者补充gpt插件了

插件大概不会用这种方案，因为这个方案好像不能在无GUI的服务器上用（

**Comment by Prometheus-first** [comment]
> 

这个不是已经获取了那些需要的信息了嘛，插件只需要把获取的信息放env里，然后运行，个人感觉是这样

**Comment by sena-nana** [comment]
> > 
> 
> 这个不是已经获取了那些需要的信息了嘛，插件只需要把获取的信息放env里，然后运行，个人感觉是这样

cf的cookie两小时刷新一次，如果你每两小时手动配置一下的话确实可以这样（

**Comment by Prometheus-first** [comment]
> > 牛哇牛哇，楼上的那位很赞，真绕过了，现在就差作者补充gpt插件了
> 
> 插件大概不会用这种方案，因为这个方案好像不能在无GUI的服务器上用（ 上游库的解决方案也是类似的，并不是很好整，感觉对于无GUI的服务器现在还是无解的状态

但是对于windows来说现在还是很友好的

**Comment by Prometheus-first** [comment]
> > > 
> > 
> > 
> > 这个不是已经获取了那些需要的信息了嘛，插件只需要把获取的信息放env里，然后运行，个人感觉是这样
> 
> cf的cookie两小时刷新一次，如果你每两小时手动配置一下的话确实可以这样（

我不怕麻烦，我只怕在QQ里再也看不到我的猫娘了T^T

**Comment by holygodly** [comment]
centos上感觉运行不了的样子

**Comment by MingxuanGame** [comment]
我用 `xvfb-run` 运行的，在我的 WSL 上是可以的

**Comment by Prometheus-first** [comment]
等等吧，现在gpt官网又崩了

**Comment by jcjrobert** [comment]
喜报，官网寄了

**Comment by Hustoking** [comment]
> 牛哇牛哇，楼上的那位很赞，真绕过了，现在就差作者补充gpt插件了

哪位啊，能否回复一下

**Comment by shoucandanghehe** [comment]
https://github.com/A-kirami/nonebot-plugin-chatgpt/pull/45#issuecomment-1347705579

**Comment by kchaifiuou** [comment]
现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie

**Comment by sena-nana** [comment]
> 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie

我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输token吧，或者发我日志看一下

**Comment by kchaifiuou** [comment]
> > 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie
> 
> 我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输令牌吧，或者发志看一下
[日志.txt](https://github.com/A-kirami/nonebot-plugin-chatgpt/files/10214620/default.txt)
token是输了的

**Comment by sena-nana** [comment]
> > > 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie
> > 
> > 
> > 我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输令牌吧，或者发志看一下
> > [日志.txt](https://github.com/A-kirami/nonebot-plugin-chatgpt/files/10214620/default.txt)
> > token是输了的

这个问题我也在调查，似乎是偶发性的？你多试几次看看

**Comment by kchaifiuou** [comment]
> > > > 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie
> > > 
> > > 
> > > 我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输令牌吧，或者发志看一下
> > > [日志.txt](https://github.com/A-kirami/nonebot-plugin-chatgpt/files/10214620/default.txt)
> > > token是输了的
> 
> 这个问题我也在调查，似乎是偶发性的？你多试几次看看

emm一上午都这样了，代理换过，token也重新输过很多次，触发指令的时候浏览器反复弹窗或者直接卡人机验证了，大佬加油
![OI U0CV6OUEN6BU6~W)EYK4](https://user-images.githubusercontent.com/120440750/207235094-c39c58f9-5fc3-4809-bb5d-3d154795beaf.png)

**Comment by sena-nana** [comment]
> > > > > 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie
> > > > 
> > > > 
> > > > 我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输令牌吧，或者发志看一下
> > > > [日志.txt](https://github.com/A-kirami/nonebot-plugin-chatgpt/files/10214620/default.txt)
> > > > token是输了的
> > 
> > 
> > 这个问题我也在调查，似乎是偶发性的？你多试几次看看
> 
> emm一上午都这样了，代理换过，token也重新输过很多次，触发指令的时候浏览器反复弹窗或者直接卡人机验证了，大佬加油 ![OI U0CV6OUEN6BU6~W)EYK4](https://user-images.githubusercontent.com/120440750/207235094-c39c58f9-5fc3-4809-bb5d-3d154795beaf.png)

目前的猜测就是这个人机验证的问题，这个是随机出现的，所以导致了问题是偶发的

**Comment by Misaga10032** [comment]
> > > > > > 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie
> > > > > 
> > > > > 
> > > > > 我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输令牌吧，或者发志看一下
> > > > > [日志.txt](https://github.com/A-kirami/nonebot-plugin-chatgpt/files/10214620/default.txt)
> > > > > token是输了的
> > > 
> > > 
> > > 这个问题我也在调查，似乎是偶发性的？你多试几次看看
> > 
> > 
> > emm一上午都这样了，代理换过，token也重新输过很多次，触发指令的时候浏览器反复弹窗或者直接卡人机验证了，大佬加油 ![OI U0CV6OUEN6BU6~W)EYK4](https://user-images.githubusercontent.com/120440750/207235094-c39c58f9-5fc3-4809-bb5d-3d154795beaf.png)
> 
> 目前的猜测就是这个人机验证的问题，这个是随机出现的，所以导致了问题是偶发的

我试了大佬你的修复方法，有时候几个问答能行，但是有的时候会跳：
请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**Comment by sena-nana** [comment]
> > > > > > > 现在似乎又寄了，绕过cf后还要输入账号密码，不然获取不到cookie
> > > > > > 
> > > > > > 
> > > > > > 我这边bot一切正常，如果是用的我的方案的话，检查一下有没有输令牌吧，或者发志看一下
> > > > > > [日志.txt](https://github.com/A-kirami/nonebot-plugin-chatgpt/files/10214620/default.txt)
> > > > > > token是输了的
> > > > 
> > > > 
> > > > 这个问题我也在调查，似乎是偶发性的？你多试几次看看
> > > 
> > > 
> > > emm一上午都这样了，代理换过，token也重新输过很多次，触发指令的时候浏览器反复弹窗或者直接卡人机验证了，大佬加油 ![OI U0CV6OUEN6BU6~W)EYK4](https://user-images.githubusercontent.com/120440750/207235094-c39c58f9-5fc3-4809-bb5d-3d154795beaf.png)
> > 
> > 
> > 目前的猜测就是这个人机验证的问题，这个是随机出现的，所以导致了问题是偶发的
> 
> 我试了大佬你的修复方法，有时候几个问答能行，但是有的时候会跳： 请求 ChatGPT 服务器时出现问题，请稍后再试 错误信息: RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

这个是chatGPT的问题，回答太长了，服务器不稳定没等生成完就断了
