### ISSUE TITLE
[Feature]: 关于配置文件保存的路径

### ISSUE THREAD

**Issue by sena-nana** [A-kirami/nonebot-plugin-chatgpt#49]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

目前配置文件的保存路径被作者修改为了和代码文件同一路径，但是个人认为这并不是一个很好的方案，希望能够讨论一下，得知作者如此修改的原因
个人认为不是好的方案的原因如下：
1. 部分python环境安装在管理员权限文件夹下，如果将配置文件置于此处可能会遇到读写权限问题
2. 不方便查看和修改配置文件内容
3. 代码与配置混在一起，文件目录结构不清晰

### 您想要的解决方案

目前大部分插件都使用data作为保存配置的目录，个人认为将配置保存在此处比较好

**Comment by A-kirami** [comment]
之前因为犯懒没加自定义配置，现在补上了
