### ISSUE TITLE
[BUG]: 收到信息之后一直卡在“Checking for matchers in priority 1...” /echo可以正常使用

### ISSUE THREAD

**Issue by 398886366** [A-kirami/nonebot-plugin-chatgpt#72]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.0

### 问题描述

卡在Checking for matchers in priority 1...

### 复现步骤

CHATGPT_PRIORITY默认是999，我改成1过后也一直卡住

### 额外补充

12-14 21:54:18 [SUCCESS] nonebot | OneBot V11 3483352424 | [message.private.friend]: Message 1690041671 from 398886366 "222"
12-14 21:54:18 [DEBUG] nonebot | Checking for matchers in priority 0...
12-14 21:54:18 [DEBUG] nonebot | Checking for matchers in priority 1...

**Comment by A-kirami** [comment]
没触发

**Comment by 398886366** [comment]
已经解决了触发的问题，然后出现了“请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: ConnectError: All connection attempts failed"
我用的是clash，代理地址填的"http:127.0.0.1:7890"
