### ISSUE TITLE
[BUG]: 12月15日windows端的智能聊天插件出现 问题，询问机器人时，机器人回复请求过多，请放慢速度，无法正常使用，昨天很正常。 

### ISSUE THREAD

**Issue by xlbl** [A-kirami/nonebot-plugin-chatgpt#75]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

v0.7.1

### 问题描述

[BUG]: 12月15日windows端的智能聊天插件出现 问题，询问机器人时，机器人回复请求过多，请放慢速度，无法正常使用，昨天很正常。 

### 复现步骤

可能是chatgpt更新了新的保护措施

**Comment by lmst2** [comment]
目前我也遇到了，官方网页端可用，cookie没有多出什么新内容，也不知道是什么新的验证会弹429

**Comment by Lu-Qi-777** [comment]
+1

**Comment by void258** [comment]
甚至换了token后第一句话都很正常，第二句就说请求过多

**Comment by xlbl** [comment]
想要作者联系方式，我好像有解决方法了

**Comment by misaka10032w** [comment]
你直接发issues里面阿

**Comment by xlbl** [comment]
![DK63WT1SJG36)SZY2)UC JK](https://user-images.githubusercontent.com/70011824/207750084-34917f90-57eb-49da-b6ea-a9624e4fa471.png)
![NNN$8TWJ R2J6R44EJZAMPF](https://user-images.githubusercontent.com/70011824/207750111-67d82fd6-bea7-4470-a8ab-ea17128cb9cb.png)
来看看这种情况，国内的无法使用，挂代理即可解决问题，但是我不知道机器人怎样挂代理。
求个大佬写个教程！

**Comment by misaka10032w** [comment]
账密好像加ReCAPTCHA了，太抠了

**Comment by misaka10032w** [comment]
代理的话开个小飞机或者clash，将env的CHATGPT_PROXIES字段配置为你的本地代理即可，例如clash配置为CHATGPT_PROXIES=http://127.0.0.1:7890
![image](https://user-images.githubusercontent.com/20655434/207750454-45b7dd7d-b336-45d0-9be3-3cf201b5ca63.png)

**Comment by misaka10032w** [comment]
但是不知道为啥，如果我挂了代理，就一直循环获取cf的cookies

**Comment by xlbl** [comment]
![image](https://user-images.githubusercontent.com/70011824/207751432-bdc47dfc-4965-49ac-aa98-5571fadbdddd.png)
我也一样，有没有更好的解决办法，我觉得咱们这应该不是正确的代理方式吧

**Comment by lmst2** [comment]
> ![DK63WT1SJG36)SZY2)UC JK](https://user-images.githubusercontent.com/70011824/207750084-34917f90-57eb-49da-b6ea-a9624e4fa471.png) ![NNN$8TWJ R2J6R44EJZAMPF](https://user-images.githubusercontent.com/70011824/207750111-67d82fd6-bea7-4470-a8ab-ea17128cb9cb.png) 来看看这种情况，国内的无法使用，挂代理即可解决问题，但是我不知道机器人怎样挂代理。 求个大佬写个教程！

奇怪，我在加拿大，也用不了

**Comment by misaka10032w** [comment]
没加cf之前配置代理是一直可以使用的

**Comment by ShanShuWu** [comment]
![image](https://user-images.githubusercontent.com/112482297/207763187-d25756c1-51bf-4c62-9cb0-5ee518edc3d8.png)
我挂了代理(

**Comment by sena-nana** [comment]
挂代理会无限获取cf，这个暂时无法解决

**Comment by xlbl** [comment]
那再等等吧，我去搞其他项目，听说AI中文模型挺好玩的

**Comment by ShanShuWu** [comment]
那目前是不是无法正常使用chatgpt的机器人了

**Comment by ShanShuWu** [comment]
> 那再等等吧，我去搞其他项目，听说AI中文模型挺好玩的

细说细说

**Comment by sena-nana** [comment]
> 那目前是不是无法正常使用chatgpt的机器人了

我这里都正常……

**Comment by xlbl** [comment]
https://air.inspur.com/home
你看看这个

**Comment by void258** [comment]
> https://air.inspur.com/home 你看看这个
这些都只开放给企业用户⑧

**Comment by xlbl** [comment]
> 
你是用的api吗？

**Comment by ShanShuWu** [comment]
我听群友说api是可以用的，但我不知道怎么弄的

**Comment by sena-nana** [comment]
我官网没开代理也没出现请求过多的情况，但是bot确实出现了这个问题

**Comment by lmst2** [comment]
> 我官网没开代理也没出现请求过多的情况，但是bot确实出现了这个问题

一样，我也是这样，官网没问题，但是机器人一直提示请求过多

**Comment by sena-nana** [comment]
找到问题原因了

**Comment by lmst2** [comment]
哦？怎么说

**Comment by ShanShuWu** [comment]
我也是今天出现这个状况，请求过多

**Comment by Prometheus-first** [comment]
问题+1，没有任何报错，换了cookie也没用，第一句就请求过多

**Comment by ShanShuWu** [comment]
没改任何东西，一觉醒来就这样了

**Comment by sena-nana** [comment]
我这边测试着，请求的过程也是什么也没有变化。甚至我网页版都刷不出请求过多的问题

**Comment by xlbl** [comment]
sena-nana请问在哪可以和你交流，我能加你qq吗？

**Comment by sena-nana** [comment]
我有novelai插件的反馈群，你可以在群里交流

**Comment by xlbl** [comment]
![GN6E6Q3V~IW_6P8EF99QRQR](https://user-images.githubusercontent.com/70011824/207814027-6d1edac1-7a4d-4d39-9cf9-2094111659ae.png)
![RO2CBVRUWDGN`_JBYN$R TE](https://user-images.githubusercontent.com/70011824/207814065-2bcaf4db-deac-4499-93db-76d145cfb2bc.png)
远程地址发生了变化从3变成了2
图一是国内网第一次请求
图二是国内网第二次请求

**Comment by lmst2** [comment]
> ![GN6E6Q3V~IW_6P8EF99QRQR](https://user-images.githubusercontent.com/70011824/207814027-6d1edac1-7a4d-4d39-9cf9-2094111659ae.png) ![RO2CBVRUWDGN`_JBYN$R TE](https://user-images.githubusercontent.com/70011824/207814065-2bcaf4db-deac-4499-93db-76d145cfb2bc.png) 远程地址发生了变化从3变成了2 图一是国内网第一次请求 图二是国内网第二次请求

这个地址应该是dns自动解析的吧，不知道咋变的

**Comment by sena-nana** [comment]
和2，3大概没关系，两个都有429的可能。目前测试可能是服务器加了其他的什么校验，因为我一开抓包就429

**Comment by Frankuzi** [comment]
[acheong08/ChatGPT](https://github.com/acheong08/ChatGPT)这个仓库都已经已经archived了，作者说要重写，其他方案好像还没出来，只能等等看了

**Comment by sena-nana** [comment]
目前尝试用单个playwright实例完全接管插件流程，并使用其api请求。但是仍然请求过多（

**Comment by sena-nana** [comment]
我解决了，最后再优化一下

**Comment by xlbl** [comment]
敬大佬

**Comment by ShanShuWu** [comment]
大佬牛逼！

**Comment by Huang-Shijie-SDUWH** [comment]
膜大佬+1

**Comment by ericzhang-debug** [comment]
同遇到这个问题，蹲一波解决方案~
