### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [A-kirami/nonebot-plugin-chatgpt#78]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

git clone ,lastest

### 问题描述

任然没办法获取cf？
我配置了代理，但没有像别人那样一直刷cf，而是直接报错如下日志了。是需要额外什么配置吗，我并没有在readme看到
ubuntu20.04,python3.9.15

### 复现步骤

正常使用对话，过了很久回复`获取session失败，请检查后台报错`

### 预期行为

正常回复（至少也回复个连接超时什么的）

### 实际行为

失败

### 日志信息

![image](https://user-images.githubusercontent.com/70925546/207901397-af61d0e2-9775-4090-a3a0-845f08634f1e.png)

**Comment by void258** [comment]
重新注册个号试试吧，我换个号就好了

**Comment by sena-nana** [comment]
更新试试
