### ISSUE TITLE
[BUG]: 超时

### ISSUE THREAD

**Issue by ShanShuWu** [A-kirami/nonebot-plugin-chatgpt#79]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.2

### 问题描述

向机器人发起对话，机器人不回应，终端报错超时

### 复现步骤

1启动机器人2向机器人发起对话

### 预期行为

正常回复

### 实际行为

机器人不回应，终端发生报错

### 日志信息

![7WIK N0C2T`XL6 HHPOBA2E](https://user-images.githubusercontent.com/112482297/208025669-9572c3e8-a1e6-4a7b-bbab-da721347ef0a.png)

**Comment by void258** [comment]
同出现这个问题

**Comment by 957549315zcl** [comment]
用token登录就不会，挂代理用账号密码登录就会超时，好像是cf获取失败

**Comment by void258** [comment]
> 

我用的就是token啊

**Comment by sena-nana** [comment]
你报错往下截

**Comment by sena-nana** [comment]
你试试把get_chat_response函数改成下面的样子能不能解决
```
    async def get_chat_response(self, prompt: str) -> str:
        async with self.get_page() as page:
            logger.debug("正在发送请求")
            if self.proxies:
                await self.get_cf_cookies(page)

            async def change_json(route: Route):
                await route.continue_(
                    post_data=json.dumps(self.get_payload(prompt)),
                )

            await self.content.route(
                "https://chat.openai.com/backend-api/conversation", change_json
            )
            await page.wait_for_selector("textarea")
            async with page.expect_response(
                "https://chat.openai.com/backend-api/conversation",
                timeout=self.timeout * 1000,
            ) as response_info:
                textarea = page.locator("textarea")
                botton = page.locator("button").last
                next=page.locator(".btn.flex.justify-center.gap-2.btn-neutral.ml-auto")
                for _ in range(3):
                    if await textarea.is_enabled():
                        await textarea.fill(prompt)
                    await page.wait_for_timeout(500)
                    if await botton.is_enabled():
                        await botton.click()
                    if await next.is_enabled():
                        await next.click()
                        await next.click()
                        await page.click(".btn.flex.justify-center.gap-2.btn-primary.ml-auto")
            response = await response_info.value
            if response.status == 429:
                return "请求过多，请放慢速度"
            if response.status == 401:
                return "token失效，请重新设置token"
            if response.status == 403:
                await self.get_cf_cookies(page)
                return await self.get_chat_response(prompt)
            if response.status != 200:
                logger.opt(colors=True).error(
                    f"非预期的响应内容: <r>HTTP{response.status}</r> {escape_tag(response.text)}"
                )
                return f"ChatGPT 服务器返回了非预期的内容: HTTP{response.status}\n{response.text}"
            lines = await response.text()
            lines = lines.splitlines()
            data = lines[-4][6:]
            response = json.loads(data)
            self.parent_id = response["message"]["id"]
            self.conversation_id = response["conversation_id"]
            logger.debug("发送请求结束")
        return response["message"]["content"]["parts"][0]
```

**Comment by tianlangxingwu** [comment]
请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: TimeoutError: Timeout 60000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response https://chat.openai.com/backend-api/conversation
============================================================
没有用捏

**Comment by black-zero358** [comment]
> # 请求 ChatGPT 服务器时出现问题，请稍后再试
> 错误信息: TimeoutError: Timeout 60000ms exceeded while waiting for event "response"
> =========================== logs ===========================
> waiting for response https://chat.openai.com/backend-api/conversation
> 没有用捏

使用命令安装的插件吗？如果是的话可以试试直接拉仓库，插件放到plugins里

**Comment by ShanShuWu** [comment]
> > # 请求 ChatGPT 服务器时出现问题，请稍后再试
> > 错误信息: TimeoutError: Timeout 60000ms exceeded while waiting for event "response"
> > =========================== logs ===========================
> > waiting for response https://chat.openai.com/backend-api/conversation
> > 没有用捏
> 
> 使用命令安装的插件吗？如果是的话可以试试直接拉仓库，插件放到plugins里

请问需要拉取哪一个，目前用的插件直接更新的0.7.2，是拉取哪一个分支吗

**Comment by black-zero358** [comment]
> > > # 请求 ChatGPT 服务器时出现问题，请稍后再试
> > > 错误信息: TimeoutError: Timeout 60000ms exceeded while waiting for event "response"
> > > =========================== logs ===========================
> > > waiting for response https://chat.openai.com/backend-api/conversation
> > > 没有用捏
> > 
> > 
> > 使用命令安装的插件吗？如果是的话可以试试直接拉仓库，插件放到plugins里
> 
> 请问需要拉取哪一个，目前用的插件直接更新的0.7.2，是拉取哪一个分支吗

https://github.com/A-kirami/nonebot-plugin-chatgpt.git
