### ISSUE TITLE
一直获取cf什么的 然后说遇到人工检验

### ISSUE THREAD

**Issue by lijun1234567** [A-kirami/nonebot-plugin-chatgpt#81]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

最新

### 问题描述

昨天还是前天已上报
居然把issue关掉了
我觉得没有解决

### 复现步骤

无

**Comment by holygodly** [comment]
建议插件整个官方api接口吧，这两天改用了openai的apikey，不仅十分稳定而且对话比chatgpt有灵性。一个印度虚拟号码差不多一块钱，可以注册两个openai账号，就是可以白嫖36刀的额度，群里人不多的话可以用几个月了。真的比白嫖token各种担心报错要好很多。。。

**Comment by sena-nana** [comment]
你确定使用的是最新版本吗，新版本这个报错已经从代码里删除了

**Comment by lijun1234567** [comment]
嗯好我再安装一下试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月16日(星期五) 下午5:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [A-kirami/nonebot-plugin-chatgpt] 一直获取cf什么的 然后说遇到人工检验 (Issue #81)





 
你确定使用的是最新版本吗，新版本这个报错已经从代码里删除了
