### ISSUE TITLE
[BUG]: 请求过多，请放慢速度

### ISSUE THREAD

**Issue by zhouwenze1** [A-kirami/nonebot-plugin-chatgpt#84]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.2

### 问题描述

无gui的ubuntu22.04
![E 07ZH%DMRWT3K)D}Y2UVQ3](https://user-images.githubusercontent.com/55984218/208069297-cec078d4-4d49-4395-bb16-96d08c552b78.png)

已经用了最新的版本了，但是并没有修复，偶尔可以成功
### 复现步骤

1.启动bot
2.向bot发送消息

### 预期行为

正常回复

### 实际行为

请求出现问题

**Comment by lijun1234567** [comment]
所以你处理好了吗
