### ISSUE TITLE
[BUG]: waiting for locator(".btn.flex.justify-center.gap-2.btn-neutral.ml-auto") to be visible

### ISSUE THREAD

**Issue by XKLibra** [A-kirami/nonebot-plugin-chatgpt#87]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

nonebot-plugin-chatgpt-0.7.2

### 问题描述

环境：
操作系统：Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)
Python 3.10.6
playwright Version 1.28.0
问题：
向bot发送信息时报错，错误在日志上

### 复现步骤

1.启动bot
2.向bot发送消息

### 预期行为

正常回复

### 实际行为

请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".btn.flex.justify-center.gap-2.btn-neutral.ml-auto") to be visible
============================================================

### 日志信息

12-16 19:54:36 [DEBUG] nonebot | Checking for matchers in priority 12...
12-16 19:54:36 [DEBUG] nonebot | Checking for matchers in priority 999...
12-16 19:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
12-16 19:54:36 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
12-16 19:54:36 [DEBUG] nonebot | Running handler Dependent(call=ai_chat, parameterless=(Depends(Dependent(call=check_cooldown)),))
12-16 19:54:40 [DEBUG] nonebot_plugin_chatgpt | 正在发送请求
12-16 19:55:10 [ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".btn.flex.justify-center.gap-2.btn-neutral.ml-auto") to be visible
============================================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/__init__.py", line 63, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 137, in get_chat_response
    await page.wait_for_selector(
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 7354, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/playwright/_impl/_page.py", line 364, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/Alicetrue/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".btn.flex.justify-center.gap-2.btn-neutral.ml-auto") to be visible
============================================================
12-16 19:55:10 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
12-16 19:55:10 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_chatgpt.utils) running complete
12-16 19:55:10 [DEBUG] nonebot | Stop event propagation

### 额外补充

我是小白，所以不是很懂

**Comment by 957549315zcl** [comment]
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".btn.flex.justify-center.gap-2.btn-neutral.ml-auto"
  selector resolved to visible <button tabindex="0" class="btn flex justify-center gap-…>Next</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #3
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #4
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #5
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #6
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #7
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #8
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #9
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #10
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #11
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #12
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #13
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #14
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #15
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #16
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #17
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #18
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #19
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #20
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #21
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #22
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #23
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #24
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #25
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #26
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #27
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #28
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #29
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #30
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #31
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #32
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #33
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #34
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #35
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #36
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #37
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #38
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #39
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #40
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #41
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #42
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #43
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #44
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #45
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #46
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #47
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #48
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #49
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #50
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #51
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #52
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #53
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #54
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #55
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #56
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #57
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #58
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #59
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #60
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #61
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex min-h-full items-end justify-center …>…</div> from <div data-headlessui-portal="">…</div> subtree intercepts pointer events
retrying click action, attempt #62
  waiting 500ms
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/LittlePaimon/bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot_plugin_chatgpt/__init__.py", line 72, in ai_chat
    await matcher.finish(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 476, in finish
    await cls.send(message, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 461, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 219, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-VcV7FQZJ-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed
我也有这个问题，顺便还弄出了adapter的问题，就更新了修复Timeout的问题的版本后才有的适配器错误，之前错误和他一样

**Comment by sena-nana** [comment]
更新0.7.3或者clone仓库使用
