### ISSUE TITLE
[BUG]: AttributeError: 'Page' object has no attribute 'get_by_role'

### ISSUE THREAD

**Issue by PrayerT** [A-kirami/nonebot-plugin-chatgpt#97]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

CommitId:36716af

### 问题描述

<img width="803" alt="image" src="https://user-images.githubusercontent.com/63850261/210035143-61ae6ad3-d549-42f1-a938-f792f4a051fe.png">
貌似是卡在了人机测试上

### 复现步骤

安装最新的版本，运行即得

### 预期行为

正常运行

### 实际行为

报错AttributeError: 'Page' object has no attribute 'get_by_role'

**Comment by wryte123** [comment]
相同问题
![image](https://user-images.githubusercontent.com/92799133/210136885-d34c0f66-152e-495e-8f75-b66bfb98dc43.png)

**Comment by HuYo-OS** [comment]
像这种情况只需要升级playwright即可

**Comment by PrayerT** [comment]
> 像这种情况只需要升级playwright即可
> 如果接下来报错AttributeError: 'NoneType' object has no attribute 'new_page'
> 可参考[#80 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/80#issuecomment-1360917617)

使用poetry run pip install playwright --upgrade之后playwright --version显示是1.29.0，问题仍然存在

**Comment by HuYo-OS** [comment]
> > 像这种情况只需要升级playwright即可
> > 如果接下来报错AttributeError: 'NoneType' object has no attribute 'new_page'
> > 可参考[#80 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/80#issuecomment-1360917617)
> 
> 使用poetry run pip install playwright --upgrade之后playwright --version显示是1.29.0，在poetry shell中启动bot问题仍然存在 按照#80的做法进行playwright install-deps，playwright install-deps chromium firefox以后问题仍然存在 是需要重启shell或者整个环境？

可以试试先把playwright完全卸载（包括删除playwright下载的文件存放路径里的所有文件），再重新运行上面命令

**Comment by PrayerT** [comment]
重新安装环境之后，问题未复现，转为[#102 ](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/102)
