### ISSUE TITLE
[BUG]: CHATGPT_COMMAND的具体使用方式什么，我在添加后无法触发

### ISSUE THREAD

**Issue by Loss-of-time** [A-kirami/nonebot-plugin-chatgpt#98]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

20221230

### 问题描述

![image](https://user-images.githubusercontent.com/51469672/210074273-233c5131-0094-4c21-b2c8-0b6f016ac70f.png)
![image](https://user-images.githubusercontent.com/51469672/210074309-7b73cd04-9754-427b-9207-5943fa14c719.png)
消息未被match

### 复现步骤

.

**Comment by wryte123** [comment]
```CHATGPT_COMMAND= [".","!","！"]```可参考这种格式

**Comment by A-kirami** [comment]
你还需要在你的消息前加上默认的nb命令前缀，通常情况下是 /
所以你的指令开头应该是 /:
